[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200